// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdZ-wKuPJvvOR23MfbMIJEXu9qse_IHmw',
    appId: '1:921558057616:web:d63b3b2aea43f5f8db8e15',
    messagingSenderId: '921558057616',
    projectId: 'alchemy-of-education',
    authDomain: 'alchemy-of-education.firebaseapp.com',
    storageBucket: 'alchemy-of-education.firebasestorage.app',
    measurementId: 'G-7WXFM2NBWV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARQWkNio7wEzEVmvkJnO9U6JB6ubZzuPs',
    appId: '1:921558057616:android:a6fe21fcbe60f275db8e15',
    messagingSenderId: '921558057616',
    projectId: 'alchemy-of-education',
    storageBucket: 'alchemy-of-education.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjLFpqnET0JYRRCp4QETPF6fI068r0rxc',
    appId: '1:921558057616:ios:e7e0a5bf2148c315db8e15',
    messagingSenderId: '921558057616',
    projectId: 'alchemy-of-education',
    storageBucket: 'alchemy-of-education.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjLFpqnET0JYRRCp4QETPF6fI068r0rxc',
    appId: '1:921558057616:ios:e7e0a5bf2148c315db8e15',
    messagingSenderId: '921558057616',
    projectId: 'alchemy-of-education',
    storageBucket: 'alchemy-of-education.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdZ-wKuPJvvOR23MfbMIJEXu9qse_IHmw',
    appId: '1:921558057616:web:f018a0c2b3b810eedb8e15',
    messagingSenderId: '921558057616',
    projectId: 'alchemy-of-education',
    authDomain: 'alchemy-of-education.firebaseapp.com',
    storageBucket: 'alchemy-of-education.firebasestorage.app',
    measurementId: 'G-4X50CYLC6X',
  );

}